spring.application.name=expense

spring.datasource.url=jdbc:mysql://yamabiko.proxy.rlwy.net:39589/railway

spring.datasource.username=root
spring.datasource.password=vbfhYeBwPWDmeHqMXUtfpVfnPUSqvxtf

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080