spring.application.name=expense

server.port=8080

# MYSQL CONFIGURATION

spring.datasource.url=jdbc:mysql://localhost:3306/smartvault

spring.datasource.username=root
spring.datasource.password=Gayathri@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# THYMELEAF

spring.thymeleaf.cache=false